apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deploy
spec:
  replicas: 3
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        version: 1.0.1
    spec:
      containers:
      - name: website
        image: ganeshhp/website:1.22
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    version: 1.0.1
# define and configure service to acces 80 port
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32402
    protocol: TCP
  selector:
    version: 1.0.1
