apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deploy
spec:
  replicas: 5
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        version: 1.0.1
    spec:
      containers:
      - name: website
        image: ganeshhp/website:latest
        ports:
        - containerPort: 80

