apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels: 
    env: prod
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 3
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: product-service 
        image: ganeshhp/php_project:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    env: prod
# define and configure service to acces 80 port
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32401
    protocol: TCP
  selector:
    env: prod

