apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-service-deploy
spec:
  replicas: 5
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: product-service 
        image: ganeshhp/php_project:latest
        ports:
        - containerPort: 80

